 Name: Shreya Vinay Nayak
 
 
 Github Username:
 
 
 USC ID: 8592810456

<center><h1>INF-552 Lab 0</h1></center>
<br>
<center><font size="4">Introduction to Basic Development Tools</font></center>

### Rules

1. Please read the instructions and problem prompts **carefully**.
2. This lab is to give you some basic APIs of numpy, pandas and scikit-learn. Besides, some topics such as how to make your jupyter notebook be a more efficient developing tools, how to use git and GitHub will also be covered. The lab is to be done individually. You may talk to your fellow classmates about general issues ("Remind me again: Which API should I used for doing group by operation to a data set") but about the specifies of how to do these exercises.
3. Along with a similar vein, you can ask the TA for help, but ask questions about **concepts** but not ask the TA to help you debug your code. The TA is here to help, but not to do the work for you.
4. You are welcome to use the class resources and the Internet.
5. Playing with variations. Solve one problems, and then copy the code to a new cell and play around with it. Doing this is the single most important thing when learning programming.
6. This lab will not be graded but the content is highly related to your future programming assignments. So, treat it wisely.
7. All the content having been gone though in the week 1 discussion is just a snapshot of the most basic concepts. **You need to keep study more about Git, GitHub, Pandas, Numpy and Scikit-Learn in order to finish your programming assignments successfully.**
8. Have fun!

### Setup Development Environment

There are many ways to setup the environment. But, I do recommend a simple idea that is using the Anaconda, which is a pre-build python environment with bundles of useful packages.

**To download the Anaconda, go to the following website:
https://www.anaconda.com/distribution/**. Download the correct version based on your operating system and install it step by step.

Then, **configure your PATH environment variable** to make the conda command work. The following command is an easy way to test whether your configuration is correct. If it is, you will see something as like as the sample output.

> **command:**
>
> conda --version
>
> **sample output:**
>
> conda 4.6.12

**Finally, download this jupyter notebook file,** then change the working directory to where its location in terminal, and type the following command to open the jupter notebook and finish the lab.

> **command:** 
> jupyter notebook

In [2]:
import pandas as pd
import numpy as np

### Pandas

#### The read_csv() Method

First, read the documentation about the *read_csv()* method in Pandas (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html). Then, try to read data from file Salaries.csv to a dataframe, make the column playerID in the csv file as the index column and the first row as the header. Also, skip the second row when reading the file.

In [18]:
df= pd.read_csv('Salaries.csv',index_col=3,header=0,skiprows=[1])
df.head(5)

yearID teamID lgID  salary
playerID                             
bedrost01    1985    ATL   NL  550000
benedbr01    1985    ATL   NL  545000
campri01     1985    ATL   NL  633333
ceronri01    1985    ATL   NL  625000
chambch01    1985    ATL   NL  800000

#### Indexing and Selecting Data

Select the id of the players who are registered in ATL and HOU and whose salary is higher than one million.

In [27]:
df_ATL= df[df['teamID'] == 'ATL']
df_ATL[df_ATL['salary']>1000000]

yearID teamID lgID    salary
playerID                               
hornebo01    1985    ATL   NL   1500000
murphda05    1985    ATL   NL   1625000
suttebr01    1985    ATL   NL   1354167
hornebo01    1986    ATL   NL   1800000
murphda05    1986    ATL   NL   1825000
...           ...    ...  ...       ...
johnske05    2015    ATL   NL   1500000
markani01    2015    ATL   NL  11000000
maybica01    2015    ATL   NL   7000000
pierzaj01    2015    ATL   NL   2000000
simmoan01    2015    ATL   NL   3000000

[325 rows x 4 columns]

In [28]:
df_ATL= df[df['teamID'] == 'HOU']
df_ATL[df_ATL['salary']>1000000]

yearID teamID lgID   salary
playerID                              
ryanno01     1985    HOU   NL  1350000
ryanno01     1986    HOU   NL  1125000
ryanno01     1987    HOU   NL  1225000
smithda02    1988    HOU   NL  1100000
clancji01    1989    HOU   NL  1225000
...           ...    ...  ...      ...
quallch01    2015    HOU   AL  3000000
rasmuco01    2015    HOU   AL  8000000
singljo02    2015    HOU   AL  2000000
sippto01     2015    HOU   AL  2400000
valbulu01    2015    HOU   AL  4200000

[270 rows x 4 columns]

#### The describe() Method

Calculate the standard Deviation, first quartile, medium, third quartile, mean, maximum, minimum of the salary in team ATL.

In [25]:

df_ATL['salary'].describe()

count    8.850000e+02
mean     2.207749e+06
std      3.434320e+06
min      6.000000e+04
25%      3.000000e+05
50%      6.000000e+05
75%      2.400000e+06
max      1.606180e+07
Name: salary, dtype: float64

#### The iterrows() Method

Create a Python dictionary object whose keys are the headers of the dataframe created in the read_csv() exercise and values are Python list objects that contain data corresponding to the headers. (Here, use the iterrows method to iterate each row of the dataframe and copy it to a dictionary. However, there is a easier way. Learn how the to_dict() method works by yourself later)

In [30]:
df.to_dict(orient='list')

{'yearID': [1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985

#### Create Dataframe Using the Constructor

Read the documentation: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html#pandas.DataFrame and create a dataframe using pd.DataFrame from the dictionary created in the iterrows() exercise. Change the header to "a", "b", "c", ... at creation time.

### Numpy

Quick start: https://www.numpy.org/devdocs/user/quickstart.html

Numpy axes explaination: https://www.sharpsightlabs.com/blog/numpy-axes-explained/

#### The np.array Method

Example 1:

```python
ls = [1, 2, 3]
arr = np.array(ls)
```

Example 2:
```python
>>> np.array([[1, 2], [3, 4]])
array([[1, 2],
       [3, 4]])
```

Now, create a 2-dimensional Python list object, then convert it to a Numpy array object.

In [14]:
import numpy as np
list=[[1,2],[4,5],[7,8]]
array=np.array(list)
print(array)

[[1 2]
 [4 5]
 [7 8]]


#### ndarray Objects' Attributes

Play with the **ndim, shape, size, dtype, itemsize and data** attribute.

Example:

```python
>>> arr = np.array([[1, 2], [3, 4]])
>>> arr.ndim
2
```

ndim represents the number of dimensions (axes) of the ndarray.

e.g. for this 2-dimensional array [ [3,4,6], [0,8,1]], value of ndim will be 2. This ndarray has two dimensions (axes) - rows (axis=0) and columns (axis=1)

In [15]:
array.ndim

2

shape is a tuple of integers representing the size of the ndarray in each dimension.

e.g. for this 2-dimensional array [ [3,4,6], [0,8,1]], value of shape will be (2,3) because this ndarray has two dimensions - rows and columns - and the number of rows is 2 and the number of columns is 3

In [16]:
array.shape

(3, 2)

size is the total number of elements in the ndarray. It is equal to the product of elements of the shape. e.g. for this 2-dimensional array [ [3,4,6], [0,8,1]], shape is (2,3), size will be product (multiplication) of 2 and 3 i.e. (2*3) = 6. Hence, the size is 6.

In [17]:
array.size

6

dtype tells the data type of the elements of a NumPy array. In NumPy array, all the elements have the same data type.

e.g. for this NumPy array [ [3,4,6], [0,8,1]], dtype will be int64

In [18]:
array.dtype

dtype('int64')

itemsize returns the size (in bytes) of each element of a NumPy array.

e.g. for this NumPy array [ [3,4,6], [0,8,1]], itemsize will be 8, because this array consists of integers and size of integer (in bytes) is 8 bytes.

In [19]:
array.itemsize


8

#### Dimension of ndarray Ojects

Play with the reshape() and flatten() method.

Example:
```python
>>> arr = np.array([[1, 2], [3, 4]])
>>> arr.flatten()
array([1, 2, 3, 4])
```

https://numpy.org/doc/stable/reference/generated/numpy.reshape.html

In [24]:
array.reshape(2,3)

array([[1, 2, 4],
       [5, 7, 8]])

In [25]:
array.flatten()

array([1, 2, 4, 5, 7, 8])

#### The Slice Operation of ndarray Objects

Understand how the slice operation works for 1-D array and 2-D array.

Example:

```python
>>> arr = np.array([[1, 2, 3], [3, 4, 6], [7, 8, 9]])
>>> arr[1:]
array([[3, 4, 6],
       [7, 8, 9]])
>>> arr[1:, 0:2]
array([[3, 4],
       [7, 8]])
```

Slicing operation of 1-D array

https://regenerativetoday.com/indexing-and-slicing-of-1d-2d-and-3d-arrays-using-numpy/

In [28]:
x = np.array([2,5,1,9,0,3,8,11,-24,-13,-18,26,10])

Here 1 is the lower limit and 7 is the upper limit.  Output array starts from the element of index 1 to 7, lower limit included and upper limit excluded.  That means it includes the element in index 1 but does not include the element in index 7.  

In [29]:
x[1:7]

array([5, 1, 9, 0, 3, 8])

Slicing with Interval: 
In this case, 2 is the starting point and 3 is the interval.  So the returning array stars from the element in index two.  After that it takes every third element of the array till the end.  



In [30]:
x[2::3]

array([  1,   3, -24,  26])

If we want to further slice it till -24

In [31]:
x[2::3][0:3]

array([  1,   3, -24])

To return the first n elements x[0:4] does the same work as x[:4]

In [32]:
x[0:4]

array([2, 5, 1, 9])

In [33]:
x[:4]

array([2, 5, 1, 9])

Slicing With Interval and Both Upper and Lower Limit:
In x[1:7:2], 1 is the lower limit, 7 is upper limit and 2 in the interval.  Output starts in the element in index 1 and end in the index 7 but instead of outputting each element in between it outputs every second element as the interval is 2. 

In [35]:
x[1:7:2]

array([5, 9, 3])

Interval Starting From The End
Here, -7 means the seventh element from the bottom or the end and 2 is the interval.  Output starts from the seventh element at the bottom and go up till the end.

In [36]:
x[-7::2]

array([  8, -24, -18,  10])

Slicing operation of 2-D array

Creation of a 6*7 2D matrix

In [3]:
import numpy as np
y = np.arange(42).reshape(6,7)
print(y)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]


To return rows of the matrix, we simply have to index the rows
Index 0 giving the first row and so on

In [4]:
y[0]

array([0, 1, 2, 3, 4, 5, 6])

To output the columns 

In [6]:
y[:,0]

array([ 0,  7, 14, 21, 28, 35])

To return one element only

In [7]:
y[4,5]

33

To get first three elements of second column:
All the elements are in rows 1,2 and 3.  The row index to use is 0:3.  Next step is to figure out the columns.  Three elements are in second column.  That is, column index 1. 


In [8]:
y[0:3, 1]

array([ 1,  8, 15])

Output a portion of the elements from first two columns shown in the matrix below
Note: Indexing for rows and columns always starts from 0
when setting the limits (lower limit, upper limit+1)

All the elements are in row 1,2 and 3.  The row index to use is 1:4.  The corresponding column indexes are 0 and 1.  So, the column indices can be represented as 0:2

In [10]:
y[1:4, 0:2]

array([[ 7,  8],
       [14, 15],
       [21, 22]])

Output this three by three subarray from the matrix:
Row indexes of the numbers are 2, 3 and 4.  So we can slice it by 2:5.  Column indexes are also 2,3 and 4.  A slice of column also can be taken by 2:5.

In [11]:
y[2:5,2:5]

array([[16, 17, 18],
       [23, 24, 25],
       [30, 31, 32]])

To print every second row from the starting from the first row:

Here 0 is the lower limit and 2 is the interval.  The output will start at index 0 and keep going till the end with an interval of 2.  That means every second row. 

In [12]:
y[0::2]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

Print every other column starting from the first column:

‘:’ means selecting all the indexes.  Here ‘:’ is selecting all the rows.  As the column input we put 0::2 (where 0 is the lower limit and 2 is the interval)

Alternative way:
In the code below 0 is the lower limit, 7 is the upper limit and 2 is the interval.  The code snippet below will output the same matrix as above. 

In [13]:
y[:,0::2]

array([[ 0,  2,  4,  6],
       [ 7,  9, 11, 13],
       [14, 16, 18, 20],
       [21, 23, 25, 27],
       [28, 30, 32, 34],
       [35, 37, 39, 41]])

In [15]:
y[:,0:7:2]

array([[ 0,  2,  4,  6],
       [ 7,  9, 11, 13],
       [14, 16, 18, 20],
       [21, 23, 25, 27],
       [28, 30, 32, 34],
       [35, 37, 39, 41]])

It is very second row starting from row 1 till the end. Lower limit 1, upper limit 6 and interval is 2.  Similarly, for the column, lower limit is 1, upper limit is 6 and interval is 2.

In [16]:
y[1:6:2,1:6:2]

array([[ 8, 10, 12],
       [22, 24, 26],
       [36, 38, 40]])

#### The Calculation of ndarray Objects

Play with the **argmin(), argmax(), min(), max(), mean(), sum(), std(), dot(), square(), sqrt(), abs(). exp(), sign(), mod()** method.

Example:

```python
>>> np.square(array)
array([[ 1,  4,  9],
       [ 9, 16, 36],
       [49, 64, 81]])

```

#### Other Important Methods Inside Module Numpy

Play with the arange(), ones(), zeros(), eye(), linspace(), concatenate() method.

Example:

```python
>>> np.eye(3)
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
```

### Scikit-Learn

The followings are packages (or methods) in Python (Scikit-Learn and Scipy) that will be frequently used in your programming assignment. So, please read carefully.

- Data Preprocessing (https://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing)
    - Standardization: StandardScaler
    - Normalization: MinMaxScaler
    - Quantifing Categorical Features: LabelEncoder. OneHotEncoder
    - Construct Train and Test Set: model_selection.train_test_split
- KNN: KNeighborsClassifier
- Linear Regression: LinearRegression
- Logistic Regression: LogisticRegression, LogisticRegressionCV
- Feature Selection / Model Selection
    - L1 Penalized Regression (Lasso Regression) with Cross-Validation: LassoCV
    - L2 Penalized Regression (Ridge Regression) with Cross-Validation: RidgeCV
    - Cross-Validation: StratifiedKFold, RepeatedKFold, LeaveOneOut, KFold, model_selection.cross_validate, model_selection.cross_val_predict, model_selection.cross_val_score
    - Model Metrics (https://scikit-learn.org/stable/modules/classes.html#sklearn-metrics-metrics): accuracy_score, auc, f1_score, hamming_loss, precision_score, recall_score, roc_auc_score
- Decision Tree: DecisionTreeClassifier, DecisionTreeRegressor
- Bootstrap, Ensemble Methods
    - Bootstrap: bootstrapped (https://pypi.org/project/bootstrapped/)
    - Bagging: RandomForestClassifier, RandomForestRegressor
    - Boosting: AdaBoostClassifier, AdaBoostRegressor
- Support Vector Machines (https://scikit-learn.org/stable/modules/svm.html#svm): LinearSVC, LinearSVR
- Multiclass and Multilabel Classification (https://scikit-learn.org/stable/modules/classes.html#module-sklearn.multiclass)
    - One-vs-one Multiclass Strategy: OneVsOneClassifier
    - One-vs-the-rest (OvR) multiclass/multilabel strategy / OneVsRestClassifier
- Unsupervised Learning
    - K-means Clustering: KMeans
    - Hierarchical Clustering: scipy.cluster.hierarchy (not scikit-learn)
- Semisupervised Learning (https://scikit-learn.org/stable/modules/label_propagation.html)

### Matplotlib

**Quick start:** https://matplotlib.org/3.1.1/tutorials/introductory/pyplot.html

**Exercises:**

(a) Create two one dimensional arrays x and y and plot y vs x, add title, xlabel, ylabel, grid.

```python
import numpy as np
import matplotlib.pyplot as plt


x = np.linspace(-5, 5, num=20)
y = np.array([j ** 2 for j in x])
```

copy the code above to the following cell and add code for plotting the parabola.

What happens if the independent variable is not sorted before plotting? Try plotting directly using the following defined array.

```python
import numpy as np
import matplotlib.pyplot as plt


x = np.linspace(-5, 5, num=20)
np.random.shuffle(x)
y = np.array([j ** 2 for j in x])
```

(b) Create multiple arrays and plot them with different styles, add legends, add text/mathematical equations on the plot.

```python
import numpy as np
import matplotlib.pyplot as plt


x = np.linspace(-5, 5, num=20)
y1 = np.array([j for j in x])
y2 = np.array([j ** 2 for j in x])
y3 = np.array([j ** 3 for j in x])
```

copy the code above to the following cell and add code for plotting curve $\left(x, y1\right)$, $\left(x, y2\right)$ and $\left(x, y3\right)$.

(c) Create multiple arrays and plot them into one figure **(No multiple figure and no subplot is allowed in this question)**.

```python
import numpy as np
import matplotlib.pyplot as plt


x = np.linspace(-5, 5, num=20)
y1 = np.array([j for j in x])
y2 = np.array([j ** 2 for j in x])
y3 = np.array([j ** 3 for j in x])
```

copy the code above to the following cell and add code for plotting curve $\left(x, y1\right)$, $\left(x, y2\right)$ and $\left(x, y3\right)$.

(d) Create multiple subplots, play around with the figure size, figure title, and its font style and font size **(One curve is plotted in one subplot in this question)**.

```python
import numpy as np
import matplotlib.pyplot as plt


x = np.linspace(-5, 5, num=20)
y1 = np.array([j for j in x])
y2 = np.array([j ** 2 for j in x])
y3 = np.array([j ** 3 for j in x])
```

copy the code above to the following cell and add code for plotting curve $\left(x, y1\right)$, $\left(x, y2\right)$ and $\left(x, y3\right)$.

(e) Change the limits on x and y axes, **use logarithmic axes to plot**.

```python
import numpy as np
import matplotlib.pyplot as plt


x = np.linspace(-5, 5, num=20)
y = np.array([j ** 2 for j in x])
```

copy the code above to the following cell and add code for plotting the parabola.

### Pandas's DataFrame.plot and Seaborn

#### Pandas's DataFrame.plot

Use the Salaries.csv again (You can use the dataframe object loaded from section 3.1).

(a) For team 'ATL', plot a scatter plot between feature yearID and salary.

(b) For year 1985, plot a bar chart to show the average salary for each team.

(c) For team 'ATL', plot a line chart to show how the annual average salary change by years.

#### Seaborn

(a) Append one more numeric feature to the data frame (can be generated randomly), then for team 'ATL', use the seaborn.pairplot to plot scatter plots among all numeric features in the data frame for team. 

(b) For year 1985 and for each team, plot a boxplot to show how the salary distribute within a team.

(c) Read the offical documentation (https://seaborn.pydata.org/) to understand how lmplot, catplot, relplot, and jointplot works.

### Jupyter Notebook

#### Jupyter Notebook Extensions

Extensions such as the code formatter, table of content is to make your development more efficient. To explore it, please refer to https://github.com/ipython-contrib/jupyter_contrib_nbextensions.

#### Jupyter Visual Debugger

The Pixie Debugger is a visual debugger for debugging on Jupyter Notebook. To explore it, please refer to https://medium.com/codait/the-visual-python-debugger-for-jupyter-notebooks-youve-always-wanted-761713babc62.

### Git and GitHub

1. In the directory that where this jupyter notebook file locates in, init a Git repository.
2. Checkout a new branch called dev and commit the current notebook within this branch.
3. Merge the dev branch to the master branch (the default branch).
4. Create a temporary repository (just for practicing and you can delete it later) in GitHub. 
5. Push new changes in the master branch to the remote repository created in step 4.
6. Checkout the dev branch again and do some changes to your notebook, and then repeat step 3 and step 5.